### PR TITLE
Prepare v0.1 release

### PR DESCRIPTION
**Pull request by tpoisot**
- [x] documentation using Documenter
- [x] use `missing` (see #5)
- [x] use `Query` (see #2)
- [x] decide on a type names convention

### CODE REVIEW

**Comment by tpoisot** [comment]
@mkborregaard I think we're close to being able to release this as a preliminary version. There is a website setup for the documentation, and all tests pass. What do you think?

**Comment by mkborregaard** [comment]
Give me a chance to have a look tomorrow. The one thing I think would be great to iron out first is the namespacing / naming of the types.

**Comment by tpoisot** [comment]
Good point -- do you mean with regard to `SpatialEcology`?

**Comment by mkborregaard** [comment]
Yes, and in general - `Occurrences` is bound to be a name many packages would want to use, also outside ecology, I guess.

**Comment by tpoisot** [comment]
Absolutely -- I have been struggling with this a bit. Here are a few quick fixes, and I'm not sure any of them are the right solution.

1) We can decide *within* EcoJulia to always be explicit about where the types (ours) come from, so `GBIF.Occurrences` instead of `Occurrences` -- advantage, it's explicit; drawback, we have no control with names outside of our own package ecosystem 
2) We preface every type with the name of the package or a short string, so `GBIFOccurrences` instead of `Occurrences` -- advantage, it's explicit; drawback, it's a bit cumbersome (but this is minimal)

My own preference would be solution 2, but I may have missed the "right" solution.

**Comment by mkborregaard** [comment]
My preference is also 2 (maybe choosing a shorter name - GBIFRecords perhaps? (there's also the capitalization to consider - GbifRecords may be better). Because with 1 we would still be in trouble if some OTHER package in Julias ecosystem exported Occurrences (because `export` is global across the session).

**Comment by tpoisot** [comment]
I think we should keep `GBIF` (and not `Gbif`) since it is an acronym.
I like the shortened names, so that would be `GBIFRecord`, `GBIFRecords`, and `GBIFTaxon` -- I'm happy with that.

**Comment by tpoisot** [comment]
@mkborregaard The doc is up to date, and the type names have been changed

**Review by mkborregaard — APPROVED** [review]
Hey, this looks great, IMHO it's ready for release. One thing, though, I think we'll need to lower-bound DataFrames to 0.11 when using the `Missings` story (I think it's best practice anyway).

I think the interface here is nicer and more intuitive than GBIF's own "rgbif" package, though this has a lot of extra functionality (I assume you've had a look).

WRT the relationship with SpatialEcology I'll look at putting that together. Importantly, SpatialEcology works with plot-type not occurrence-type data. I talked to a guy at GBIF and he said they actually do have plot-type data, but I'm not sure how and how to access it. I'm meeting the GBIF people next week and will ask them, that would make for very nice integration.
I do think SpatialEcology should at the least define an abstact occurrence type too, which GBIFRecord could possibly inherit from.
(A fun discussion of the capilization of GBIFRecord and such things is found here https://github.com/JuliaPraxis/Naming/issues/4 :smile: )

**Pull request merged**
